### ISSUE TITLE
Hardcoded regexp prevents users from changing the marker

### ISSUE THREAD

**Issue by skx** [amno1/lite#1]
This code:

```
(defun lite-template-in-line-p ()
  "Whether there is at least one template in a line."
  (save-excursion
    (goto-char (line-end-position))
    (re-search-backward "%%" (line-beginning-position) t)))
```

Should presumably use `lite-marker-regex` instead of the hardcoded default value?

**Comment by amno1** [comment]
Of course; thank you very much. It just slipped through.

**Comment by skx** [comment]
No problem.

Thanks for posting your code, it was nice to read and it looks like it could be useful to me in the future :)

**Comment by amno1** [comment]
Thank you. I appreciate the feedback.
